# MERIDIAN CONSTANTS
MERIDIAN_DATE_FORMAT = '%Y-%m-%dT%H:%M:00.000Z'
MERIDIAN_PARSE_DATE_FORMAT = '%Y-%m-%dT%H:%M:00Z'
MERIDIAN_BASE_ODDS = 0
MERIDIAN_DOUBLE_CHANCE_ODDS = 1
MERIDIAN_SPORT_FOOTBALL_ID = 58
MERIDIAN_ODDS_BETS = (MERIDIAN_BASE_ODDS, MERIDIAN_DOUBLE_CHANCE_ODDS)

# SANSA CONSTANTS
SANSA_SPORT_FOOTBALL_ID = 0
SANSA_PARSE_DATE_FORMAT = '%Y-%m-%dT%H:%M:00.0000000+01:00'

# LOB CONSTANTS
LOB_BASE_ODDS_CODE = 3131
LOB_DOUBLE_CHANCE_CODE = 3130
LOB_DATE_FORMAT = '%Y.%d.%m. %H:%M'

# LVBET CONSTANTS
LVBET_BASE_ODDS_CODE = 16
LVBET_DOUBLE_CHANCE_ODDS_CODE = 4

# MAXBET CONSTANTS
MAXBET_BASE_ODDS_CODE = 70
MAXBET_DOUBLE_CHANCE_CODE = 71