"""
Django settings for sure_bet project.

Generated by 'django-admin startproject' using Django 2.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import environ

env = environ.Env()
env.read_env(env.str('ENV_PATH', '.env'))

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5u&xdfg=%)@j71z%)11gv(6^^o_en1^iy5@9k2un6yyasj$&zr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bettings',
    'gateways',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sure_bet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sure_bet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env("DATABASE_NAME"),
        'USER': env("DATABASE_USER"),
        'PASSWORD': env("DATABASE_PASSWORD"),
        'HOST': env("DATABASE_HOST"),
        'PORT': env("DATABASE_PORT"),
    },
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# BETTING PLACE SCAPER CLIENTS
SCRAPER_CLIENT_SPORT_URLS = {
    'OLIMPWIN': {
        'FOOTBALL': 'https://olimpwin.com/sports/?t=-60#2/0/0/0/'
    },
    'ZLATNIK': {
        'FOOTBALL': 'https://www.zlatnik.me/srl/sports-betting/offer/fudbal?hours={}'
    },
    'ADMIRAL': {
        'FOOTBALL': 'https://www.admiralbet.me/sport-prematch?sport=Fudbal',
    },
    'MERIDIAN': {
        'FOOTBALL': 'https://meridianbet.me/sr/kladjenje/fudbal',
    },
    'VOLCANO': {
        'FOOTBALL': 'https://www.volcanobet.me/prematch/1?time-filter={}',
    },
    'SBBET': {
        'FOOTBALL': 'https://sbbet.me/sport?&event_type=upcoming',
    },
    'PREMIER': {
        'FOOTBALL': 'https://www.premierbet.me/sport/football-betting',
    },
}

# BETTING PLACE API CLIENTS
DIRECT_CLIENT_SPORT_URLS = {
    'VOLCANO': {
        'FOOTBALL': {
            'url': 'https://sportdataprovider.volcanobet.me/api/public/prematch/SportEvents',
            'params': {
                    'SportId': 1,
                    'timezone': -60,
                    'clientType': 'WebConsumer',
                    'v': '1.1.2113-rc.2',
                    'lang': 'sr-Latn-ME',
            },
        },
    },
    'ZLATNIK': {
        'FOOTBALL': {
            'url': 'https://apis.zlatnik.me/SportOfferApi/api/sport/offer/v3/sports/offer',
            'params': {
                'SportIds': 388,
                'Offset': 0,
                'Limit': 1000,
            },
        },
    },
    'MERIDIAN': {
        'FOOTBALL': {
            'url': {
                'events': 'https://meridianbet.me/sails/sport/58/multiple-leagues-with-league/{league_id}/date/{date}/timeFilter/threeDays/filterPositions/{bet_group},0,0',
                'leagues': 'https://meridianbet.me/sails/sidebars/standard',
            },
            'params': {

            },
        },
    },
    'SANSA': {
        'FOOTBALL': {
            'url': {
                'events': 'https://sansabet.com/Oblozuvanje.aspx/GetLiga',
                'leagues': 'https://sansabet.com/Oblozuvanje.aspx/GetSportoviSoLigi',
            },
            'params': {
                'leagues': {
                    "filter": "0",
                    "activeStyle": "img/sports",
                },
            },
        },
    },
    'LOB': {
        'FOOTBALL': {
            'url': 'https://www.lobbet.me/ibet/offer/matches/today/S.json?v=4.36.7&locale=sr_ME&ttgIds=S@{bet_code}',
        },
    },
    'LVBET': {
        'FOOTBALL': {
            'url': 'https://app.lvbet.com/_api/v1/offer/matches/?is_live=false&sports_groups_ids=5&lang=en',
        },
    },
    'MAXBET': {
        'FOOTBALL': {
            'url': 'https://www.maxbet.me/ibet/offer/leagues//25/2.json?v=4.38.1&locale=sr_ME&token=117827%23117683%23117709%23137588%23148566%23132134%23185898%23126605%23169337%23152565%23132125%23132230%23146768%23141348%23157439%23157440%23146491%23186311%23168173%23157458%23160175%23146650%23177588%23138547%23132379%23134715%23152568%23174109%23119606%23131843%23142836%23176580%23117751%23175249%23132231%23152556%23131946%23169380%23132462%23133866%23130522%23152524%23146161%23149958%23176581%23152558%23132128%23177149%23169547%23132791%23152559%23132737%23175171%23134088%23117696%23169371%23122647%23117710%23117651%23169437%23119607%23176090%23172071%23146813&ttgIds=S@{bet_code}',
        },
    },
}

