# Generated by Django 4.0.1 on 2022-01-09 14:00

import bettings.enums
from django.db import migrations, models
from bettings.integrations.betting_places import enums as bet_place_enums
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_home', models.CharField(max_length=50)),
                ('player_away', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('sport', models.IntegerField(choices=[(1, 'football')], default=bettings.enums.Sports['FOOTBALL'])),
                ('league', models.CharField(blank=True, max_length=150, null=True)),
                ('tournament', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sport_match',
            },
        ),
        migrations.CreateModel(
            name='BetOdds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betting_institution', models.IntegerField(choices=[(1, 'OLIMP kladionica')], default=bet_place_enums.BettingInstitutions['OLIMPWIN'])),
                ('odds', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bettings.match')),
            ],
            options={
                'db_table': 'sport_match_odds',
            },
        ),
    ]
