# Generated by Django 4.0.1 on 2022-01-22 16:50

import bettings.enums
import bettings.integrations.betting_places.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='batch',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='betodds',
            name='betting_institution',
            field=models.IntegerField(choices=[(1, 'OLIMP'), (2, 'ZLATNIK'), (3, 'ADMIRAL'), (4, None)], default=bettings.integrations.betting_places.enums.BettingInstitutions['OLIMPWIN']),
        ),
        migrations.AlterField(
            model_name='match',
            name='sport',
            field=models.IntegerField(choices=[(1, 'FOOTBALL')], default=bettings.enums.Sports['FOOTBALL']),
        ),
    ]
