# Generated by Django 4.0.1 on 2022-01-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettings', '0002_match_batch_alter_betodds_betting_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='betting_institution',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
